#Minecraft server properties
#Tue May 12 21:21:47 HKT 2026
border_color=-16777216
customize_border=false
hide_border=true
remove_screen_background=true
show_debug_info=false
sync_with_os_theme=true
system_backdrop_type=DWMSBT_TRANSIENTWINDOW
transparent_window=true
use_immersive_dark_mode=false
window_corner_preference=DWMWCP_DEFAULT
