#CustomSteve Debug Window UI Settings
#Sun Apr 26 19:39:26 HKT 2026
fontPath=
fontSize=20.0
snapshotAutoFreezeDRel=true
snapshotAutoFreezeRel=false
snapshotAutoFreezeSubsteps=true
snapshotAutoFreezeTele=false
snapshotBudgetMB=2048
snapshotCaptureBodyStates=true
snapshotCaptureSubsteps=true
snapshotDRelThreshold=0.2
snapshotEnabled=false
snapshotExportPath=A\:\\Minecraft\\.minecraft\\versions\\Cogwheel-Heavyworks-NH\\customsteve_debug\\physics_snapshots
snapshotRelThreshold=0.5
snapshotSubstepsThreshold=12
snapshotTier=2
uiScale=1.5
