#AnimGraphEditor layout
#Wed Apr 15 16:55:51 HKT 2026
__condition__\:ItemWaveRight=843.0,-148.0
__condition__\:attack_bare_left=-421.0,524.0
__condition__\:attack_bare_right=-421.0,215.0
__condition__\:attack_item_left=-421.0,1214.0
__condition__\:attack_item_right=-421.0,421.0
__condition__\:attack_shield_left_left=-421.0,766.0
__condition__\:attack_shield_right_right=-421.0,3547.0
__condition__\:attack_spear_left=-421.0,3928.0
__condition__\:attack_spear_right=-421.0,905.0
__condition__\:attack_stick_left=-421.0,1626.0
__condition__\:attack_stick_right=-421.0,1111.0
__condition__\:attacking_left_hand=-422.0,4483.0
__condition__\:attacking_right_hand=-421.0,1317.0
__condition__\:bow_draw_left=-421.0,2038.0
__condition__\:bow_draw_right=-421.0,1523.0
__condition__\:bracing_left=-421.0,2244.0
__condition__\:bracing_right=-421.0,1729.0
__condition__\:crossbow_draw_left=2972.0,30.0
__condition__\:crossbow_draw_right=2972.0,133.0
__condition__\:eat_left=-418.0,4146.0
__condition__\:eat_right=-421.0,1935.0
__condition__\:item_hold_left=-421.0,41.0
__condition__\:item_hold_right=-394.0,2158.0
__condition__\:left_hand_shield=-419.0,3218.0
__condition__\:left_hand_weapon=-421.0,627.0
__condition__\:mc.airborne\ \=\=\ true=-380.0,2807.0
__condition__\:mc.bodyState\ \=\=\ idle_battle=-421.0,1008.0
__condition__\:mc.creativeFlying\ \=\=\ true=-421.0,2517.0
__condition__\:mc.groundDistance\ >\ 3=-421.0,3032.0
__condition__\:mc.riding\ \=\=\ true=-421.0,2723.0
__condition__\:mc.sneaking\ \=\=\ true=-421.0,318.0
__condition__\:player_only_playback=2195.0,-125.0
__condition__\:right_hand_shield=-421.0,2347.0
__condition__\:right_hand_weapon=-421.0,2432.0
__condition__\:shield_hold_left_left=-421.0,3426.0
__condition__\:shield_hold_right_right=-421.0,2620.0
__condition__\:shield_parry_left_left=-420.0,3685.0
__condition__\:shield_parry_right_right=-421.0,3305.0
__condition__\:spear_hold_left=-421.0,1832.0
__condition__\:spear_hold_right=-421.0,3825.0
__condition__\:stick_hold_left=-421.0,1420.0
__condition__\:stick_hold_right=-419.0,4031.0
__condition__\:using_left_hand=-421.0,3135.0
__condition__\:using_right_hand=-420.0,4310.0
__expr__\:action\:boots_armor=1718.0,273.0
__expr__\:action\:chest_armor=1717.0,471.0
__expr__\:action\:socks_white=1715.0,40.0
__output__=1748.0,1638.0
action_left\:attack_bare_left=499.0,390.0
action_left\:attack_item_left=499.0,807.0
action_left\:attack_shield_left=499.0,946.0
action_left\:attack_spear_left=499.0,529.0
action_left\:attack_stick_left=499.0,668.0
action_left\:bow_draw_left=499.0,1363.0
action_left\:bracing_left=499.0,1224.0
action_left\:crossbow_draw_left=3892.0,30.0
action_left\:eat_left=499.0,1502.0
action_left\:item_hold_left=499.0,1641.0
action_left\:shield_hold_left=606.0,1999.0
action_left\:shield_parry_left=499.0,1085.0
action_left\:spear_hold_left=799.0,112.0
action_left\:stick_hold_left=799.0,233.0
action_right\:attack_bare_right=40.0,888.0
action_right\:attack_item_right=110.0,1322.0
action_right\:attack_shield_right=70.0,1460.0
action_right\:attack_spear_right=181.0,994.0
action_right\:attack_stick_right=245.0,1052.0
action_right\:bow_draw_right=143.0,2144.0
action_right\:bracing_right=108.0,1907.0
action_right\:crossbow_draw_right=3592.0,30.0
action_right\:eat_right=144.0,2497.0
action_right\:item_hold_right=618.0,-431.0
action_right\:shield_hold_right=421.0,-223.0
action_right\:shield_parry_right=112.0,1842.0
action_right\:spear_hold_right=1668.0,-486.0
action_right\:stick_hold_right=77.0,154.0
body\:boat_driving_battle=799.0,838.0
body\:boat_driving_idle=799.0,1322.0
body\:boat_moving=799.0,959.0
body\:boat_moving_left=799.0,1080.0
body\:boat_moving_right=799.0,1201.0
body\:elytra=1099.0,475.0
body\:fall=799.0,475.0
body\:fall_jump=799.0,354.0
body\:fly_idle=1099.0,717.0
body\:fly_move=1099.0,596.0
body\:idle=-263.0,2874.0
body\:idle_battle=2652.0,195.0
body\:jump=799.0,596.0
body\:ladder=1099.0,1080.0
body\:ladderDown=1099.0,959.0
body\:ladderUp=1099.0,838.0
body\:riding=799.0,1564.0
body\:riding_horse=799.0,1443.0
body\:run=1099.0,1443.0
body\:sleep=1099.0,112.0
body\:sneak_idle=1098.0,1322.0
body\:sneak_walk=1099.0,1201.0
body\:swim=1099.0,354.0
body\:swimming=1099.0,233.0
body\:turn=799.0,717.0
body\:walk=1099.0,1564.0
player_only_playback\:player_only_playback=1761.0,677.0
upper_body\:attack_item_up=496.0,-737.0
upper_body\:attack_spear_up=71.0,1565.0
upper_body\:attack_stick_up=210.0,1414.0
upper_body\:barehanded_up=31.0,687.0
upper_body\:bow_draw_up=-89.0,-556.0
upper_body\:bracing_up=180.0,1329.0
upper_body\:crossbow_draw_up=3292.0,30.0
upper_body\:eat_up=39.0,351.0
upper_body\:hold_bow_up=1191.0,-154.0
upper_body\:hold_crossbow_loaded_up=4212.0,30.0
upper_body\:hold_crossbow_up=3292.0,169.0
upper_body\:hold_item_right=71.0,535.0
upper_body\:hold_spear_up=103.0,490.0
upper_body\:hold_stick_up=260.0,-90.0
upper_body\:punch_left_up=-463.0,-252.0
upper_body\:punch_right_up=1670.0,905.0
